name: E2E WebdriverIO Tests
on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  
jobs:
  release:
    environment: Release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-24.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev build-essential libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev webkit2gtk-driver xvfb

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: init install folder (Windows)
        if: matrix.platform == 'windows-latest'
        run: ${{ github.workspace }}\init.ps1
      - name: init install folder (Linux & Mac)
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'macos-latest'
        run: ${{ github.workspace }}/init.sh                
                
      - name: E2E Linux
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          cd webdriver/webdriverio
          npm i
          ./run_e2e.sh

      - name: E2E Windows
        if: matrix.platform == 'windows-latest'
        run: |
          Invoke-WebRequest -URI https://msedgedriver.azureedge.net/121.0.2227.0/edgedriver_win64.zip -OutFile $Env:temp\edgedriver_win64.zip
          Expand-Archive -Path $Env:temp\edgedriver_win64.zip -DestinationPath C:\Windows\SysWOW64
          cd webdriver\webdriverio
          npm i
          .\run_e2e.ps1
  
